services:
  openclaw-gateway:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    hostname: openclaw-gateway
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      OPENCLAW_GATEWAY_PORT: ${OPENCLAW_GATEWAY_PORT:-18789}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_HOSTNAME: openclaw-gateway
    volumes:
      - openclaw-config-dir:/home/node/.openclaw
      - openclaw-workspace-dir:/home/node/.openclaw/workspace
      - openclaw-linuxbrew-dir:/home/node/.linuxbrew
      - tailscale-state:/var/lib/tailscale
    init: true
    restart: unless-stopped
    entrypoint: ["/app/docker-entrypoint.sh"]
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "18789",
      ]

  openclaw-cli:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      BROWSER: echo
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - openclaw-config-dir:/home/node/.openclaw
      - openclaw-workspace-dir:/home/node/.openclaw/workspace
    network_mode: "service:openclaw-gateway"
    depends_on:
      - openclaw-gateway
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]

volumes:
  tailscale-state:
  openclaw-config-dir:
  openclaw-workspace-dir:
  openclaw-linuxbrew-dir:
